Fixes: When the user clicks login a type error is shown for the first time, then the second click it works.
Error: type List<dynamic> is not a subtype of type Map<String, dynamic> #8

Changes: replace [insertMany] mongoose function with [create] as insertMany will wrap the object within an array. For the second hit backend will just update existing token with [findOneAndUpdate] function so it will override array with the single object.